<?php include VIEW . 'header.phtml'; ?>
<div class="ctl">
<article>

    <div class="filter">
        <button><a href="/home/entries">All entries</a></button>
        <button><a href="/home/entries/filter=europe">Europe</a></button>
        <button><a href="/home/entries/filter=asia">Asia</a></button>
        <button><a href="/home/entries/filter=america">America</a></button>
    </div>

<?php



if (array_key_exists('all', $this->view_data)){
    $table = '';

    foreach ($this->view_data['all'] as $entry) {
                 $table .= '<table class="wpisy"><thead><tr><th class="thtytul">' . $entry['tytul'] . '</th><th class="thdata">Dodano: ' . $entry['data'] . '</th></tr></thead>
                             <tbody><tr><td colspan=\"2\">' . $entry['tresc'] . '</td></tr></tbody></table><br/><br/>';
    }

    $table.='</table>';
    echo $table;

} else { echo 'Tablica nie istnieje! Wystąpił błąd.';}

?>
    </article>

</div>

<?php include VIEW.'footer.phtml'; ?>
