<!DOCTYPE html>
<html>
<head>
    <meta charset-="UTF-8">
    <link rel="stylesheet" href="/style.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster|Raleway" rel="stylesheet">
</head>
<body>
    <header>
        <div class="header_content">My travel blog</div>
        <div class="header_site">by Andrzej Chuchra</div>
    </header>
    <ul class="navi">
        <li><a href="/home/index">Home - about me</a></li>
        <li><a href="/home/entries">My entries</a></li>
    </ul>